"use client";
import { useState } from "react";

import { Dialog, DialogTrigger, DialogContent } from "@/components/ui/dialog";

import TransactionForm from "@/components/TransactionForm";
import TransactionList from "@/components/TransactionList";

//TS imports
type Transaction = {
  _id: string; //unique id , automatically generated by mongoDB while storing data
  amount: number;
  date: string;
  description: string;
};

export default function Home() {
  const [open, setOpen] = useState(false); //state variable used to display 'TransactionForm'.

  //This will store the selected transaction when you click the edit(pencil) button.
  const [editableTx, setEditableTx] = useState<Transaction | null>(null);

  return (
    <main className="max-w-xl mx-auto p-4">
      <h1 className="text-2xl font-bold mb-6">Personal Finance Visualizer</h1>
      <Dialog open={open} onOpenChange={setOpen}>
        <DialogTrigger asChild>
          <button
            className="bg-gradient-to-r from-blue-500 to-indigo-500 text-white px-6 py-2 rounded-xl shadow-md hover:shadow-lg hover:from-blue-600 hover:to-indigo-600 transition-all duration-300"
            onClick={() => setOpen(true)}
          >
            ➕ Add Transaction
          </button>
        </DialogTrigger>

        <DialogContent>
          <TransactionForm
            onSuccess={() => setOpen(false)}
            onClose={() => {
              setOpen(false);
              setEditableTx(null);
            }}
            editableTx={editableTx} //send transaction to edit
          ></TransactionForm>
        </DialogContent>
      </Dialog>
      <TransactionList
        setShowForm={setOpen}
        setEditableTx={setEditableTx}
      ></TransactionList>
    </main>
  );
}
